name: Update TryHackMe Badge

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install jq -y

      - name: Fetch THM avatar via API
        run: |
          mkdir -p assets
          AVATAR_URL=$(curl -s https://tryhackme.com/api/user/JUWON | jq -r '.user.avatar')

          echo "Avatar URL: $AVATAR_URL"

          if [ "$AVATAR_URL" = "null" ] || [ -z "$AVATAR_URL" ]; then
            echo "Failed to fetch avatar"
            exit 1
          fi

          curl -L "$AVATAR_URL" -o assets/thm.png

      - name: Commit
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add assets/thm.png
          git commit -m "update thm badge" || echo "no changes"
          git push
