name: Update TryHackMe Badge

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update THM badge
        run: |
          mkdir -p assets
          curl -o assets/thm.png https://tryhackme-badges.s3.amazonaws.com/JUWON.png

      - name: Commit
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add assets/thm.png
          git commit -m "update thm badge" || echo "no changes"
          git push
